version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 51212:51212
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432