# Dockerfile.vercel
FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ENV DATABASE_URL="dummy"
RUN npx prisma generate
RUN npm run build

FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.output ./.output
COPY entrypoint.vercel.sh ./entrypoint.vercel.sh
RUN chmod +x ./entrypoint.vercel.sh

ENV PORT=80
ENTRYPOINT ["/app/entrypoint.vercel.sh"]