name: DataBaseMigrationCI

on:
  push:
    branches: [ stg, main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install depencendies
        run: npm ci
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run DB migration
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}